Model:
    name: "MISNet"

Train:
    Dataset:
        type: "PolypDataset"
        root: "../data/TrainDataset"
        transform_list:
            resize: 
                size: [352, 352]
            random_scale_crop:
                range: [0.75, 1.25]
            random_flip:
                lr: True
                ud: True
            random_rotate:
                range: [0, 359]
            random_image_enhance:
                methods: ['contrast', 'sharpness', 'brightness']
            random_dilation_erosion:
                kernel_range: [2, 5]
            random_gaussian_blur:
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 16
        shuffle: True
        num_workers: 8
        pin_memory: False
    Optimizer:
        type: "Adam"
        lr: 1.0e-05
        weight_decay: 1.0e-05
        clip: 0.5
        mixed_precision: False
    Scheduler:
        type: "PolyLr"
        epoch: 300
        gamma: 0.9
        minimum_lr: 1.0e-07
        warmup_iteration: 30
    Checkpoint:
        checkpoint_epoch: 20
        checkpoint_dir: "snapshots/MISNet"


Test:
    Dataset:
        type: "PolypDataset"
        root: "../data/TestDataset"
        testsets: ['CVC-300', 'CVC-ClinicDB', 'CVC-ColonDB', 'ETIS-LaribPolypDB', 'Kvasir']
        transform_list:
            resize: 
                size: [352, 352]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 0
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "./snapshots/MISNet"
        results_dir: "./results/MISNet"

Eval:
    gt_root: "../data/TestDataset"
    pred_root: "./results/MISNet"
    result_path: "./eval_results/MISNet"
    datasets: ['CVC-300', 'CVC-ClinicDB', 'CVC-ColonDB', 'ETIS-LaribPolypDB', 'Kvasir']
    metrics: ['meanDic', 'meanIoU', 'wFm', 'Sm', 'meanEm', 'mae', 'maxEm', 'maxDic', 'maxIoU', 'meanSen', 'maxSen', 'meanSpe', 'maxSpe']

